# Use an official PHP runtime as a parent image
FROM php:8.2-cli

# Set the working directory in the container
WORKDIR /app

# Run the specified PHP script when the container launches
CMD ["sh", "-c", "php /app/$SCRIPT_NAME"]