# Use an official GNU Smalltalk runtime as a parent image
FROM codesignal/smalltalk:v12.0.0

# Set the working directory in the container
WORKDIR /app

# Run the Smalltalk script
CMD ["sh", "-c", "gst /app/$SCRIPT_NAME"]