# Use an official R runtime as a parent image
FROM r-base:latest

# Set the working directory in the container
WORKDIR /app

# Run the specified R script when the container launches
CMD ["sh", "-c", "Rscript /app/$SCRIPT_NAME"]
