# Use an official Python runtime as a parent image
FROM python:3.13-slim

# Set the working directory in the container
WORKDIR /app

# Run the specified Python script when the container launches
CMD ["sh", "-c", "python /app/$SCRIPT_NAME"]