# Use an official Clojure runtime as a parent image
FROM clojure:latest

# Set the working directory in the container
WORKDIR /app

# Run the specified Clojure script when the container launches
CMD ["sh", "-c", "clojure /app/$SCRIPT_NAME"]
